. "$LAB_LIB"
in_repo proj diff --cached --name-only | grep -qx '\.gitignore' || fail ".gitignore is not staged."
in_repo proj diff --cached --name-only | grep -qx 'app.js' || fail "app.js is not staged."
! in_repo proj diff --cached --name-only | grep -qx 'debug.log' || fail "debug.log should not be staged."
! in_repo proj diff --cached --name-only | grep -qx '\.env' || fail ".env should not be staged."
! in_repo proj diff --cached --name-only | grep -E '^tmp/' || fail "Files under tmp/ should not be staged."
[ -f proj/debug.log ] || fail "debug.log must remain on disk."
[ -f proj/.env ] || fail ".env must remain on disk."
[ -f proj/tmp/cache.txt ] || fail "tmp/cache.txt must remain on disk."